"""GitHub PR automation for AI-SDLC workflow.

Usage:
  python workflow/git_workflow.py create-pr --branch DATA-123/my-feature --jira-id DATA-123
  python workflow/git_workflow.py review-pr --pr-number 42
  python workflow/git_workflow.py merge-pr --pr-number 42
  python workflow/git_workflow.py clone --repo-url https://github.com/org/repo.git --target-dir tmp/opsbuddy-fix/OPS-1
  python workflow/git_workflow.py create-branch --repo-dir tmp/opsbuddy-fix/OPS-1 --branch OPS-1/hotfix-oom --base main
  python workflow/git_workflow.py commit --repo-dir tmp/opsbuddy-fix/OPS-1 --message "OPS-1: fix OOM" --files a.py b.py
  python workflow/git_workflow.py push --repo-dir tmp/opsbuddy-fix/OPS-1 --branch OPS-1/hotfix-oom
"""

from __future__ import annotations

import os
import subprocess
import sys
import tempfile
import textwrap
from contextlib import contextmanager
from pathlib import Path
from typing import Optional

import click
from github import Auth, Github
from rich.console import Console

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from python.utils.config import get, require  # noqa: E402
from python.utils.logger import get_logger  # noqa: E402
from workflow.jira_workflow import JiraClient  # noqa: E402

logger = get_logger(__name__)
console = Console()


class GitHubClient:
    def __init__(self, repo: Optional[str] = None) -> None:
        """`repo` (owner/name) defaults to $GITHUB_REPO -- but a job/incident can be backed by
        a repo other than whatever that env var happens to be set to (confirmed in practice:
        GITHUB_REPO pointed at dev_ops while a diagnosis on a different job needed to target
        the insightops repo instead). Always pass the repo resolved by opsbuddy-fix's
        get-repo-mapping step rather than relying on the default when one is available.
        """
        self.gh = Github(auth=Auth.Token(require("GITHUB_TOKEN")))
        self.repo = self.gh.get_repo(repo or require("GITHUB_REPO"))

    def create_pr(
        self, branch: str, title: str, body: str, base: str = "main"
    ) -> object:
        pr = self.repo.create_pull(
            title=title,
            body=body,
            head=branch,
            base=base,
        )
        logger.info(f"Created PR #{pr.number}: {pr.html_url}")
        return pr

    def get_pr(self, pr_number: int) -> object:
        return self.repo.get_pull(pr_number)

    def merge_pr(self, pr_number: int, merge_method: str = "squash") -> None:
        pr = self.get_pr(pr_number)
        if not pr.mergeable:
            raise RuntimeError(
                f"PR #{pr_number} is not mergeable (status: {pr.mergeable_state})"
            )
        pr.merge(merge_method=merge_method)
        logger.info(f"Merged PR #{pr_number}")

    def get_pr_checks(self, pr_number: int) -> list[dict]:
        pr = self.get_pr(pr_number)
        commit = pr.get_commits().reversed[0]
        return [
            {
                "name": check.name,
                "status": check.status,
                "conclusion": check.conclusion,
            }
            for check in commit.get_check_runs()
        ]

    def check_access(self) -> dict:
        """Verify the configured token can see this repo and has push access.

        Note: this reflects the authenticated actor's overall repo permission level,
        not a fine-grained PAT's specific granted scopes (GitHub doesn't expose those
        via the REST API) — a token can pass this check and still lack, e.g., the
        Pull Requests scope needed to actually open a PR. Treat this as a fast-fail
        for wrong repo/token/no-access cases, not a full scope guarantee.
        """
        can_push = bool(self.repo.permissions and self.repo.permissions.push)
        return {
            "repo": self.repo.full_name,
            "default_branch": self.repo.default_branch,
            "push_access": can_push,
        }


def build_pr_body(
    jira_id: str, ticket_summary: str, ticket_description: str, changes_summary: str
) -> str:
    jira_url = (
        f"{get('JIRA_BASE_URL', 'https://your-org.atlassian.net')}/browse/{jira_id}"
    )
    return textwrap.dedent(
        f"""
        ## Summary

        **Jira Ticket:** [{jira_id}]({jira_url}) — {ticket_summary}

        {ticket_description[:500]}{"..." if len(ticket_description) > 500 else ""}

        ## Changes

        {changes_summary}

        ## Checklist

        - [ ] DBT models run without errors (`make dbt-run`)
        - [ ] All DBT tests pass (`make dbt-test`)
        - [ ] Python unit tests pass (`make py-test`)
        - [ ] SQL follows sqlfluff style guide (`make lint`)
        - [ ] Schema YAML updated with new columns / tests
        - [ ] No hardcoded credentials

        ---
        *Auto-generated by AI-SDLC workflow*
    """
    ).strip()


def get_git_diff_summary() -> str:
    result = subprocess.run(
        ["git", "diff", "main...HEAD", "--stat"], capture_output=True, text=True
    )
    return result.stdout.strip() or "No diff available"


def _run_git(*args: str, cwd: str, env: Optional[dict] = None) -> str:
    result = subprocess.run(
        ["git", *args], cwd=cwd, capture_output=True, text=True, env=env
    )
    if result.returncode != 0:
        raise RuntimeError(f"git {' '.join(args)} failed: {result.stderr.strip()}")
    return result.stdout.strip()


def _with_token_auth(repo_url: str) -> str:
    """Embed the `x-access-token` username into an https:// GitHub URL.

    `x-access-token` is GitHub's well-known placeholder username for token auth — it
    is not a secret, so it's safe to persist in the clone's remote URL. The actual
    token is never embedded in the URL; it's supplied per-request via GIT_ASKPASS
    (see `_git_auth_env`), so it never lands in `.git/config` or shell history.
    """
    token = get("GITHUB_TOKEN", "")
    if (
        not token
        or not repo_url.startswith("https://")
        or "@" in repo_url.split("://", 1)[1]
    ):
        return repo_url
    return repo_url.replace("https://", "https://x-access-token@", 1)


@contextmanager
def _git_auth_env():
    """Yield an env dict that authenticates git HTTPS operations with GITHUB_TOKEN,
    without ever writing the token to disk or hanging on an interactive/GUI prompt
    (e.g. Windows Git Credential Manager) when no ambient credentials are configured.
    """
    token = get("GITHUB_TOKEN", "")
    if not token:
        yield os.environ.copy()
        return

    fd, askpass_path = tempfile.mkstemp(suffix=".sh")
    try:
        with os.fdopen(fd, "w") as f:
            f.write('#!/bin/sh\necho "$GIT_PUSH_TOKEN"\n')
        os.chmod(askpass_path, 0o700)
        env = os.environ.copy()
        env["GIT_ASKPASS"] = askpass_path
        env["GIT_PUSH_TOKEN"] = token
        env["GIT_TERMINAL_PROMPT"] = "0"
        env["GCM_INTERACTIVE"] = "Never"
        yield env
    finally:
        if os.path.exists(askpass_path):
            os.remove(askpass_path)


class GitRepoManager:
    """Raw git working-tree plumbing (clone/branch/commit/push) for automated hotfix flows.

    Unlike GitHubClient (PyGithub, talks to the GitHub API for PRs/reviews/merges), this
    operates on a local clone via the `git` CLI — needed since PyGithub has no local
    working-tree operations.
    """

    def __init__(self, repo_dir: str) -> None:
        self.repo_dir = repo_dir

    @classmethod
    def clone(cls, repo_url: str, target_dir: str) -> "GitRepoManager":
        parent = Path(target_dir).parent
        parent.mkdir(parents=True, exist_ok=True)
        auth_url = _with_token_auth(repo_url)
        with _git_auth_env() as env:
            _run_git(
                "-c",
                "credential.helper=",
                "clone",
                auth_url,
                str(Path(target_dir).resolve()),
                cwd=str(parent),
                env=env,
            )
        logger.info(f"Cloned {repo_url} -> {target_dir}")
        manager = cls(target_dir)
        manager._configure_author()
        return manager

    def _configure_author(self) -> None:
        name = get("OPSBUDDY_GIT_AUTHOR_NAME", "opsbuddy-fix-bot")
        email = get(
            "OPSBUDDY_GIT_AUTHOR_EMAIL", "opsbuddy-fix-bot@users.noreply.github.com"
        )
        _run_git("config", "user.name", name, cwd=self.repo_dir)
        _run_git("config", "user.email", email, cwd=self.repo_dir)

    def create_branch(self, branch_name: str, base: str = "main") -> None:
        _run_git("checkout", base, cwd=self.repo_dir)
        with _git_auth_env() as env:
            _run_git(
                "-c",
                "credential.helper=",
                "pull",
                "origin",
                base,
                cwd=self.repo_dir,
                env=env,
            )
        _run_git("checkout", "-b", branch_name, cwd=self.repo_dir)
        logger.info(f"Created branch {branch_name} from {base}")

    def commit(self, message: str, paths: list[str]) -> str:
        _run_git("add", *paths, cwd=self.repo_dir)
        _run_git("commit", "-m", message, cwd=self.repo_dir)
        sha = _run_git("rev-parse", "HEAD", cwd=self.repo_dir)
        logger.info(f"Committed {sha[:8]}: {message}")
        return sha

    def push(self, branch_name: str, remote: str = "origin") -> None:
        with _git_auth_env() as env:
            _run_git(
                "-c",
                "credential.helper=",
                "push",
                "-u",
                remote,
                branch_name,
                cwd=self.repo_dir,
                env=env,
            )
        logger.info(f"Pushed {branch_name} to {remote}")


# ── CLI ───────────────────────────────────────────────────────────────────────


@click.group()
def cli():
    pass


@cli.command("create-pr")
@click.option("--branch", required=True, help="Feature branch name")
@click.option("--jira-id", required=True, help="Jira ticket ID (e.g. DATA-123)")
@click.option("--base", default="main", help="Base branch to merge into")
@click.option(
    "--repo",
    default=None,
    help="owner/repo to target -- defaults to $GITHUB_REPO. Pass the repo opsbuddy-fix's "
    "get-repo-mapping resolved when it differs from the configured default.",
)
@click.option(
    "--body-file",
    default=None,
    help="Path to file containing PR body (skips auto-generation)",
)
def cmd_create_pr(
    branch: str, jira_id: str, base: str, repo: Optional[str], body_file: Optional[str]
):
    """Create a GitHub PR from the current branch, linked to a Jira ticket."""
    try:
        jira = JiraClient()
        ticket = jira.get_ticket(jira_id)
    except Exception as e:
        logger.warning(f"Could not fetch Jira ticket: {e}")
        ticket = None

    summary = ticket.summary if ticket else branch
    title = f"[{jira_id}] {summary}"

    if body_file:
        with open(body_file, "r", encoding="utf-8") as f:
            body = f.read()
    else:
        description = ticket.description if ticket else ""
        diff_stat = get_git_diff_summary()
        body = build_pr_body(jira_id, summary, description, diff_stat)

    gh = GitHubClient(repo=repo)
    pr = gh.create_pr(branch=branch, title=title, body=body, base=base)
    click.echo(f"[OK] PR created: {pr.html_url}")

    if ticket:
        # Try "In Review" first; fall back to "In Progress" if unavailable
        for transition_name in ("In Review", "In Progress"):
            try:
                jira.transition_ticket(jira_id, transition_name)
                click.echo(f"[OK] Jira {jira_id} transitioned to '{transition_name}'")
                break
            except ValueError:
                continue
        jira.add_comment(jira_id, f"PR created: {pr.html_url}")


@cli.command("review-pr")
@click.option("--pr-number", required=True, type=int, help="PR number")
@click.option(
    "--repo", default=None, help="owner/repo to target -- defaults to $GITHUB_REPO"
)
def cmd_review_pr(pr_number: int, repo: Optional[str]):
    """Show PR status and CI check results."""
    gh = GitHubClient(repo=repo)
    pr = gh.get_pr(pr_number)
    checks = gh.get_pr_checks(pr_number)

    console.print(f"\n[bold]PR #{pr_number}[/bold]: {pr.title}")
    console.print(f"State: {pr.state} | Mergeable: {pr.mergeable}")
    console.print(f"URL: {pr.html_url}\n")

    for check in checks:
        icon = "[OK]" if check["conclusion"] == "success" else "[FAIL]"
        click.echo(f"  {icon} {check['name']}: {check['conclusion']}")


@cli.command("merge-pr")
@click.option("--pr-number", required=True, type=int, help="PR number")
@click.option("--jira-id", default=None, help="Jira ticket ID to close after merge")
@click.option(
    "--method", default="squash", type=click.Choice(["merge", "squash", "rebase"])
)
@click.option(
    "--repo", default=None, help="owner/repo to target -- defaults to $GITHUB_REPO"
)
def cmd_merge_pr(
    pr_number: int, jira_id: Optional[str], method: str, repo: Optional[str]
):
    """Merge a PR and optionally close the Jira ticket."""
    gh = GitHubClient(repo=repo)
    gh.merge_pr(pr_number, merge_method=method)
    click.echo(f"[OK] PR #{pr_number} merged")

    if jira_id:
        jira = JiraClient()
        jira.transition_ticket(jira_id, "Done")
        jira.add_comment(jira_id, f"PR #{pr_number} merged to main. Ticket closed.")
        click.echo(f"[OK] Jira {jira_id} closed")


@cli.command("clone")
@click.option(
    "--repo-url",
    required=True,
    help="Git URL to clone (e.g. https://github.com/org/repo.git)",
)
@click.option("--target-dir", required=True, help="Local directory to clone into")
def cmd_clone(repo_url: str, target_dir: str):
    """Clone a repo into a local working directory."""
    GitRepoManager.clone(repo_url, target_dir)
    click.echo(f"[OK] Cloned into {target_dir}")


@cli.command("create-branch")
@click.option("--repo-dir", required=True, help="Path to the local clone")
@click.option("--branch", required=True, help="New branch name")
@click.option("--base", default="main", help="Base branch to branch from")
def cmd_create_branch(repo_dir: str, branch: str, base: str):
    """Create a new branch off `base` in an existing local clone."""
    GitRepoManager(repo_dir).create_branch(branch, base=base)
    click.echo(f"[OK] Branch {branch} created from {base}")


@cli.command("commit")
@click.option("--repo-dir", required=True, help="Path to the local clone")
@click.option("--message", required=True, help="Commit message")
@click.option(
    "--files",
    required=True,
    multiple=True,
    help="File path(s) to stage — repeat the flag, or pass a comma-separated list",
)
def cmd_commit(repo_dir: str, message: str, files: tuple):
    """Stage and commit specific files in an existing local clone."""
    file_list = [f.strip() for group in files for f in group.split(",") if f.strip()]
    sha = GitRepoManager(repo_dir).commit(message, file_list)
    click.echo(f"[OK] Committed {sha}")


@cli.command("push")
@click.option("--repo-dir", required=True, help="Path to the local clone")
@click.option("--branch", required=True, help="Branch name to push")
@click.option("--remote", default="origin", help="Remote name")
def cmd_push(repo_dir: str, branch: str, remote: str):
    """Push a branch from a local clone to the remote."""
    GitRepoManager(repo_dir).push(branch, remote=remote)
    click.echo(f"[OK] Pushed {branch} to {remote}")


@cli.command("check-access")
def cmd_check_access():
    """Verify GITHUB_TOKEN can see GITHUB_REPO and has push access (fast preflight check)."""
    result = GitHubClient().check_access()
    click.echo(
        f"[OK] Repo: {result['repo']} (default branch: {result['default_branch']})"
    )
    if result["push_access"]:
        click.echo("[OK] Push access: yes")
    else:
        click.echo("[WARN] Push access: no — clone/push/PR steps will likely fail")


if __name__ == "__main__":
    cli()
